ALTER TABLE user_profiles ADD COLUMN age INT;
ALTER TABLE user_profiles ADD COLUMN gender VARCHAR(50);
ALTER TABLE user_profiles ADD COLUMN goal VARCHAR(100);
ALTER TABLE user_profiles ADD COLUMN diet_type VARCHAR(100);
ALTER TABLE user_profiles ADD COLUMN lifestyle_class VARCHAR(50);
ALTER TABLE user_profiles ADD COLUMN meal_budget VARCHAR(50);
ALTER TABLE user_profiles ADD COLUMN favorite_foods VARCHAR(255);
ALTER TABLE user_profiles ADD COLUMN disliked_foods VARCHAR(255);
ALTER TABLE user_profiles ADD COLUMN bmr DOUBLE PRECISION;
ALTER TABLE user_profiles ADD COLUMN tdee DOUBLE PRECISION;
ALTER TABLE user_profiles ADD COLUMN daily_calories_target INT;
ALTER TABLE user_profiles ADD COLUMN protein_target INT;
ALTER TABLE user_profiles ADD COLUMN carbs_target INT;
ALTER TABLE user_profiles ADD COLUMN fats_target INT;
